version: "3.8"

services:
  backend:
    build: ./backend
    container_name: resume_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: resume_frontend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
